### ISSUE TITLE
Expect any attribute

### ISSUE THREAD

**Issue by Kansuler** [gusaul/go-dynamock#6]
Hello,

When you define the expected dynamodb.AttributeValues - Is it possible to somehow expect any value for some of the attributes when passing them along to WithItems method. I tried to use nil, but it seems like it doesn't work.

**Comment by gusaul** [comment]
Hi, sorry for late response,

if you want to expect any value, it means you don't expect anything, you can just simply ignore the expectation and go ahead to determine the result only

``` go
mock.ExpectGetItem().WillReturns(result)
```

i hope this help, thanks

**Comment by Kansuler** [comment]
Thanks for your help!
